# Configuration file for KinectFusionApp

data_path = "/home/christian/share/dataset/"
recording_name = "woman"

# Input camera settings
[camera]
#type = "Pseudo"
#type = "Xtion"
type = "RealSense"

[camera.realsense]
live = true

# KinectFusion pipeline settings
[kinectfusion]
# The overall size of the volume (in mm). Will be allocated on the GPU and is thus limited by the amount of
# storage you have available. Dimensions are (x, y, z).
volume_size = [ 512, 512, 512 ]

# The amount of mm one single voxel will represent in each dimension. Controls the resolution of the volume.
voxel_scale = 2.0

# Parameters for the Bilateral Filter, applied to incoming depth frames.
# Directly passed to cv::cuda::bilateralFilter(...); for further information, have a look at the opencv docs.
bfilter_kernel_size = 5
bfilter_color_sigma = 1.0
bfilter_spatial_sigma = 1.0

# The initial distance of the camera from the volume center along the z-axis (in mm)
init_depth = 1000.0

# Downloads the model frame for each frame (for visualization purposes). If this is set to true, you can
# retrieve the frame with Pipeline::get_last_model_frame()
use_output_frame = true

# The truncation distance for both updating and raycasting the TSDF volume
truncation_distance = 25.0

# The distance (in mm) after which to set the depth in incoming depth frames to 0.
# Can be used to separate an object you want to scan from the background
depth_cutoff_distance = 1500.0

# The number of pyramid levels to generate for each frame, including the original frame level
num_levels = 3

# The maximum buffer size for exporting triangles; adjust if you run out of memory when exporting
triangles_buffer_size = 6000000
# The maximum buffer size for exporting pointclouds; adjust if you run out of memory when exporting
pointcloud_buffer_size = 6000000

# ICP configuration
# The distance threshold (as described in the paper) in mm
distance_threshold = 10.0
# The angle threshold (as described in the paper) in degrees
angle_threshold = 20.0
# Number of ICP iterations for each level from original level 0 to highest scaled level (sparse to coarse)
icp_iterations = [ 4, 5, 10 ]